[package]
name = "sshctl"
version = "0.1.7"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }
dialoguer = "0.12.0"
dirs = "6.0.0"
log = "0.4.28"
serde = { version = "1.0.223", features = ["derive"] }
thiserror = "2.0.16"
toml = "0.9.5"
