name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    uses: ./.github/workflows/build-linux.yml
    with:
      version: ${{ github.ref_name }}

  create-release:
    needs: build-linux
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
