name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags v1.0.0, v2.1.0, etc.
  workflow_dispatch:  
    inputs:
      version:
        description: 'Version tag (e.g., v0.1.5)'
        required: true
        default: 'v0.0.0-test'

jobs:
  # Build Linux
  build-linux:
    uses: ./.github/workflows/build-linux.yml
    with:
      version: ${{ github.event.inputs.version || github.ref_name }}

  # Create GitHub release
  create-release:
    needs: build-linux
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          files: ./dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Update AUR package
  update-aur:
    needs: create-release
    uses: ./.github/workflows/update-aur.yml
    with:
      version: ${{ github.event.inputs.version || github.ref_name }}
    secrets: inherit
